In [394]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans #para clasificar los datos
import sklearn as sk #para normalizar los datos
import seaborn as sns
from sklearn import tree

In [770]:
path1= 'C:/Users/alejandro/Desktop/ProyectoFinal Delfin/Limpiados/incidenciaMunicipal_2015_vivienda.csv'
df_Vivienda=pd.read_csv(path1,low_memory=False,index_col=0)

In [771]:
df_Vivienda.head()

CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  FEBRERO  MARZO  \
0        1        1        6        15           16      4        3      0   
1        1        1        6        15           17      9       10     10   
2        1        1        6        15           18      4        1      5   
3        1        1        6        15           19      0        0      0   
4        1        1        6        15           20     34       32     46   

   ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  NOVIEMBRE  \
0      7     4      6      4       3           4        1          4   
1     11    11      6     10      18           8        3         14   
2      3     0      1      1       4           2        5          6   
3      0     1      0      0       0           0        0          1   
4     44    49     34     49      56          34       24         49   

   DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH_2015  
0          7             43                      3  
1         14            115                      3  
2          4             32                      3  
3          0              2                      3  
4         32            449                      3

In [772]:
dicc_el=['CVE_MOD','ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SEPTIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE']

In [773]:
df_Vivienda.VIVIENDA_ENDUTIH_2015.value_counts()

0    22902
2    15048
1    11220
3     4488
Name: VIVIENDA_ENDUTIH_2015, dtype: int64

In [774]:
df_copy=df_Vivienda.copy()

In [775]:
df_copy.drop(dicc_el, axis=1,inplace=True)

In [776]:
df_copy.head()

CVE_ENT  CVE_MUN  CVE_TIPO  CVE_SUBTIPO  TOTAL_DELITOS  \
0        1        1        15           16             43   
1        1        1        15           17            115   
2        1        1        15           18             32   
3        1        1        15           19              2   
4        1        1        15           20            449   

   VIVIENDA_ENDUTIH_2015  
0                      3  
1                      3  
2                      3  
3                      3  
4                      3

In [787]:
df_copy=df_copy[['CVE_ENT','CVE_MUN','VIVIENDA_ENDUTIH_2015','CVE_TIPO','TOTAL_DELITOS']]
df_copy.head()

CVE_ENT  CVE_MUN  VIVIENDA_ENDUTIH_2015  CVE_TIPO  TOTAL_DELITOS
0        1        1                      3        15             43
1        1        1                      3        15            115
2        1        1                      3        15             32
3        1        1                      3        15              2
4        1        1                      3        15            449

In [788]:
from sklearn.model_selection import train_test_split

In [789]:
X = df_copy[df_copy.columns[0:4]].values
X.shape

(53658, 4)

In [790]:
y = np.array(df_copy[df_copy.columns[4:]])
y.shape

(53658, 1)

In [880]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123234)

In [881]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [882]:
regr = RandomForestRegressor(bootstrap=False,max_depth=8,min_samples_split=2
                             , random_state=132)

In [883]:
regr.fit(X_train,y_train)

C:\Users\alejandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=8,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=132, verbose=0, warm_start=False)

In [884]:
o=regr.predict(X_test)
regr.score(X_test,y_test)

0.17008134987633272

In [885]:
o = (o).astype('int')
o

array([ 4,  6,  3, ...,  4,  5, 10])

In [886]:
hits = 0

for i in range(1,len(o)):
    if(o[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/o.shape[0])*100), '%')

performance: 7 %


In [823]:
from sklearn.ensemble import GradientBoostingRegressor

In [833]:
est = GradientBoostingRegressor(n_estimators=100, learning_rate=0.3,max_depth=8, random_state=12, loss='lad')

In [834]:
est.fit(X_train, y_train)

C:\Users\alejandro\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.3, loss='lad', max_depth=8, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=12,
             subsample=1.0, verbose=0, warm_start=False)

In [835]:
o=est.predict(X_test)
o=(o).astype('int')
o

array([0, 0, 0, ..., 0, 0, 0])

In [836]:
hits = 0

for i in range(1,len(o)):
    if(o[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/o.shape[0])*100), '%')

performance: 63 %


In [603]:
import scipy.special as sigmoid
import pandas as pd

In [604]:
# neural network class definition
class neuralNetwork:
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        self.wih = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: sigmoid.expit(x)
        
        pass
    
    # predict
    def predict(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
        pass
    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), 
                                        np.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), 
                                        np.transpose(inputs))
        
        pass

In [869]:
# number of input, hidden and output nodes
input_nodes = X_train.shape[1]
hidden_nodes = 300
output_nodes = 1

# learning rate is 0.3
learning_rate = 0.00000003

# create instance of neural network
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [870]:
n.train(X_train, y_train)

In [871]:
o = n.predict(X_test)
o = (o).astype('int')
o=(o).T
o

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [872]:
hits = 0

for i in range(1,len(o)):
    if(o[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/o.shape[0])*100), '%')

performance: 66 %


In [841]:
from sklearn.naive_bayes import GaussianNB

In [842]:
gnb = GaussianNB()

In [847]:
gnb.fit(X_train, y_train)

C:\Users\alejandro\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [848]:
o=gnb.predict(X_test)

In [849]:
o

array([538, 469,   0, ..., 325, 529, 392], dtype=int64)

In [850]:
hits = 0

for i in range(1,len(o)):
    if(o[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/o.shape[0])*100), '%')

performance: 19 %
